/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <string>
#include "Printer.H"
#define INDENT_WIDTH 2


//You may wish to change render
void PrintAbsyn::render(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppend(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppend('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppend(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ' ') bufAppend(c);
  else if (c == 0) return;
  else
  {
     bufAppend(c);
     bufAppend(' ');
  }
}

void PrintAbsyn::render(String s)
{
  render(s.c_str());
}

bool allIsSpace(const char *s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return false;
  return true;
}

void PrintAbsyn::render(const char *s)
{
  if (*s) /* C string not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppend(s);
    } else {
      bufAppend(s);
      bufAppend(' ');
    }
  }
}

void PrintAbsyn::indent()
{
  int n = _n_;
  while (--n >= 0)
    bufAppend(' ');
}

void PrintAbsyn::backup()
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void PrintAbsyn::removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppend('\n');
  indent();
}

PrintAbsyn::PrintAbsyn(void)
{
  _i_ = 0; _n_ = 0;
  buf_ = 0;
  bufReset();
}

PrintAbsyn::~PrintAbsyn(void)
{
}

char *PrintAbsyn::print(Visitable *v)
{
  _i_ = 0; _n_ = 0;
  bufReset();
  v->accept(this);
  return buf_;
}

void PrintAbsyn::visitListReg(ListReg *listreg)
{
  iterListReg(listreg->begin(), listreg->end());
}

void PrintAbsyn::iterListReg(ListReg::const_iterator i, ListReg::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render('&'); iterListReg(i+1, j);
  }
}

void PrintAbsyn::visitReg(Reg *p) {} //abstract class

void PrintAbsyn::visitRReg(RReg *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->exp_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExp(Exp *p) {} //abstract class

void PrintAbsyn::visitEConcat(EConcat *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 1; visitListExp(p->listexp_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEUnion(EUnion *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  _i_ = 2; visitListExp(p->listexp_);

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEStar(EStar *p)
{
  int oldi = _i_;
  if (oldi > 3) render(_L_PAREN);

  _i_ = 3; p->exp_->accept(this);
  render('*');

  if (oldi > 3) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEMore(EMore *p)
{
  int oldi = _i_;
  if (oldi > 3) render(_L_PAREN);

  _i_ = 3; p->exp_->accept(this);
  render('+');

  if (oldi > 3) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitERepe(ERepe *p)
{
  int oldi = _i_;
  if (oldi > 3) render(_L_PAREN);

  _i_ = 3; p->exp_->accept(this);
  render('?');

  if (oldi > 3) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEMult(EMult *p)
{
  int oldi = _i_;
  if (oldi > 3) render(_L_PAREN);

  _i_ = 3; p->exp_->accept(this);
  visitRang(p->rang_);

  if (oldi > 3) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEClas(EClas *p)
{
  int oldi = _i_;
  if (oldi > 3) render(_L_PAREN);

  render('[');
  _i_ = 0; visitListSymb(p->listsymb_);
  render(']');

  if (oldi > 3) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEAStr(EAStr *p)
{
  int oldi = _i_;
  if (oldi > 3) render(_L_PAREN);

  _i_ = 0; visitListSymb(p->listsymb_);

  if (oldi > 3) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListExp(ListExp *listexp)
{
  iterListExp(listexp->begin(), listexp->end());
}

void PrintAbsyn::iterListExp(ListExp::const_iterator i, ListExp::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    switch(_i_)
    {
      case 2: (*i)->accept(this);
              render('|');
              iterListExp(i+1, j); break;
      case 1: (*i)->accept(this); iterListExp(i+1, j); break;
    }
  }
}

void PrintAbsyn::visitListSymb(ListSymb *listsymb)
{
  iterListSymb(listsymb->begin(), listsymb->end());
}

void PrintAbsyn::iterListSymb(ListSymb::const_iterator i, ListSymb::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    visitSymb(*i);
  }
  else
  { /* cons */
    visitSymb(*i); iterListSymb(i+1, j);
  }
}

void PrintAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  render(tmp);
}

void PrintAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  render(tmp);
}

void PrintAbsyn::visitChar(Char c)
{
  char tmp[4];
  sprintf(tmp, "'%c'", c);
  render(tmp);
}

void PrintAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
  bufAppend(' ');
}

void PrintAbsyn::visitIdent(String s)
{
  render(s);
}

void PrintAbsyn::visitSymb(String s)
{
  render(s);
}


void PrintAbsyn::visitRang(String s)
{
  render(s);
}


ShowAbsyn::ShowAbsyn(void)
{
  buf_ = 0;
  bufReset();
}

ShowAbsyn::~ShowAbsyn(void)
{
}

char *ShowAbsyn::show(Visitable *v)
{
  bufReset();
  v->accept(this);
  return buf_;
}

void ShowAbsyn::visitListReg(ListReg *listreg)
{
  for (ListReg::const_iterator i = listreg->begin() ; i != listreg->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listreg->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitReg(Reg *p) {} //abstract class

void ShowAbsyn::visitRReg(RReg *p)
{
  bufAppend('(');
  bufAppend("RReg");
  bufAppend(' ');
  bufAppend('[');
  if (p->exp_)  p->exp_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitExp(Exp *p) {} //abstract class

void ShowAbsyn::visitEConcat(EConcat *p)
{
  bufAppend('(');
  bufAppend("EConcat");
  bufAppend(' ');
  bufAppend('[');
  if (p->listexp_)  p->listexp_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitEUnion(EUnion *p)
{
  bufAppend('(');
  bufAppend("EUnion");
  bufAppend(' ');
  bufAppend('[');
  if (p->listexp_)  p->listexp_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitEStar(EStar *p)
{
  bufAppend('(');
  bufAppend("EStar");
  bufAppend(' ');
  bufAppend('[');
  if (p->exp_)  p->exp_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitEMore(EMore *p)
{
  bufAppend('(');
  bufAppend("EMore");
  bufAppend(' ');
  bufAppend('[');
  if (p->exp_)  p->exp_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitERepe(ERepe *p)
{
  bufAppend('(');
  bufAppend("ERepe");
  bufAppend(' ');
  bufAppend('[');
  if (p->exp_)  p->exp_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitEMult(EMult *p)
{
  bufAppend('(');
  bufAppend("EMult");
  bufAppend(' ');
  bufAppend('[');
  if (p->exp_)  p->exp_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitRang(p->rang_);
  bufAppend(')');
}
void ShowAbsyn::visitEClas(EClas *p)
{
  bufAppend('(');
  bufAppend("EClas");
  bufAppend(' ');
  bufAppend('[');
  if (p->listsymb_)  p->listsymb_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitEAStr(EAStr *p)
{
  bufAppend('(');
  bufAppend("EAStr");
  bufAppend(' ');
  bufAppend('[');
  if (p->listsymb_)  p->listsymb_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListExp(ListExp *listexp)
{
  for (ListExp::const_iterator i = listexp->begin() ; i != listexp->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listexp->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitListSymb(ListSymb *listsymb)
{
  for (ListSymb::const_iterator i = listsymb->begin() ; i != listsymb->end() ; ++i)
  {
    visitSymb(*i) ;
    if (i != listsymb->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppend(tmp);
}
void ShowAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppend(tmp);
}
void ShowAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufAppend(c);
  bufAppend('\'');
}
void ShowAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}
void ShowAbsyn::visitIdent(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}

void ShowAbsyn::visitSymb(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}


void ShowAbsyn::visitRang(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}



